### ISSUE TITLE
bad log level in readme?

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/whistlepunk#10]
i noticed the readme file uses `level: 5` in a few places, but it looks like the officially supported levels are 0 - 4. 

was the `level:5` intentional? or should that be updated to `level: 4` in those cases?

**Comment by arobson** [comment]
@derickbailey I'm not entirely sure why 5 was used but it's using a numeric comparison so it just makes SUPER SURE? I have no problem changing it to 4 at all.
