### ISSUE TITLE
remove default "whistlepunk" namespace?

### ISSUE THREAD

**Issue by derickbailey** [LeanKit-Labs/whistlepunk#11]
Is there a particular reason for having the logger namespace default to "whistlepunk"?

https://github.com/LeanKit-Labs/whistlepunk/blob/master/src/Logger.js#L8

in my apps, I would prefer the default namespace to be an empty string, so that I don't have to manually specify a namespace every time i create a logger. most of the time, I don't want a namespace at all, and having it default to "whistlepunk" makes it look like it's the whistlepunk module is doing the logging, instead of my code.

**Comment by arobson** [comment]
@derickbailey We can change this to an empty string as well. In our case, we use it enough that we always provide a namespace so we know what module/lib is producing messages, but defaulting it to whistlepunk doesn't provide us with any benefit. :+1:
